### PR TITLE
add fixed bytes

### PR DESCRIPTION
**Pull request by ca1e**
depending on https://wiki.gbatemp.net/wiki/Amiibo, add some fixed bytes data

### CODE REVIEW

**Comment by hax0kartik** [comment]
Was testing done with wummibo?

**Comment by ca1e** [comment]
Hi, unlucky I dont have a 3ds for test, but when I walking through the wummibo's source code I found that it only read the byte of specified offset,so I promise it will works fine with wummibo!

**Comment by hax0kartik** [comment]
May I know why do you want these bytes to be added? Like does this make the amiibo bins work some place else?

**Comment by ca1e** [comment]
these bytes can be used to generate encrypted amiibo directly by just random the uid bytes

**Comment by ca1e** [comment]
thank you for trusting me,if any thing goes wrong,plz let me know,I'd happy to fix it.

**Comment by hax0kartik** [comment]
@ca1e As suspected this actually broke amiibo cards in animal crossing happy home designer. Seems to be related to cfg0/cfg1/dlok block.

**Pull request merged**
