### PR TITLE
Fix bin generation code

### PR DESCRIPTION
**Pull request by DanTheMan827**
Did it ever generate correct bins? 0x1DC is nowhere near where the identification block should go.

I also added the appropriate static lock, cc, dynamic lock, and cfg bytes

Everything is still in decrypted form though.

### CODE REVIEW

**Comment by DanTheMan827** [comment]
Oh, my bad, wumiibo must have a different data layout...

**Comment by DanTheMan827** [comment]
@hax0kartik

**Comment by hax0kartik** [comment]
I'm sorry for the super late reply, been busy this week. Ill take a look this evening.

**Comment by hax0kartik** [comment]
So I took a look and I would like the things to remain as it is. Also doesn't tagmo write encrypted bins to tags?

**Comment by DanTheMan827** [comment]
Tagmo writes bin files, if you write an encrypted one you get a usable tag, if you write a decrypted one, you get a usable tag that needs the app data reset

**Pull request closed without merging**
